name: Hello World Workflow

on: 
  push:
    branches:
      - '*'

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a Hello World script
      run: echo "Hello, World!"
